// AUTO-GENERATED by scripts/set-env.js from environment variables.
// Override with API_BASE_URL and PRODUCTION (e.g. in a .env file).
// Defaults: API_BASE_URL=/api, PRODUCTION=false
export const environment = {
  production: false,
  apiBaseUrl: '/api',
};
