// Generates src/environments/environment.ts from environment variables so the
// API base URL and production flag aren't hardcoded. Run automatically by the
// `prestart` / `prebuild` npm hooks. Defaults reproduce the committed file.
const fs = require('fs');
const path = require('path');

try {
  require('dotenv').config({ quiet: true });
} catch {
  /* dotenv is optional */
}

const apiBaseUrl = process.env.API_BASE_URL || '/api';
const production = String(process.env.PRODUCTION || 'false').toLowerCase() === 'true';

const content = `// AUTO-GENERATED by scripts/set-env.js from environment variables.
// Override with API_BASE_URL and PRODUCTION (e.g. in a .env file).
// Defaults: API_BASE_URL=/api, PRODUCTION=false
export const environment = {
  production: ${production},
  apiBaseUrl: '${apiBaseUrl}',
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.writeFileSync(outPath, content);
console.log(`[set-env] apiBaseUrl='${apiBaseUrl}' production=${production}`);
